print('Gustavo Rios Benitez')
print('Departmento de Sistemas')
print('Facultad de Ciencias Economicas, Universidad de Buenos Aires')
print('Itapiru 3362')
print('Lanús, Buenos Aires, 1824')
print('Argentina')
